# -*- coding: utf-8 -*-
"""Klasyfikacja - budowanie bazy danych do projektu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYcppW8hd1bCUmyQME2c_Kx6h25IucUN
"""

import pandas as pd
import numpy as np
import requests
import time
import json

page = "https://api-football-v1.p.rapidapi.com/v3/leagues"

headers = {
	"X-RapidAPI-Key": "b5416357fdmshbf77b855e1c384cp1088b4jsncccf260f6a3b",
	"X-RapidAPI-Host": "api-football-v1.p.rapidapi.com"
}

leagues = requests.request("GET", page, headers=headers)

leagues.json()

url = "https://api-football-v1.p.rapidapi.com/v3/players"

headers = {
	"X-RapidAPI-Key": "b5416357fdmshbf77b855e1c384cp1088b4jsncccf260f6a3b",
	"X-RapidAPI-Host": "api-football-v1.p.rapidapi.com"
}

result = []

for i in range(1,38):
	querystring = {"league": "39", "season":"2020", 'page' : i}
	response = requests.get(url, headers=headers, params=querystring)
	content = response.json()
	result.append(content)
	print(f"Getting Premier League data from page {i}")
	time.sleep(5)

for i in range(1,38):
	querystring = {"league": "61", "season":"2020", 'page' : i}
	response = requests.get(url, headers=headers, params=querystring)
	content = response.json()
	result.append(content)
	print(f"Getting Ligue 1 data from page {i}")
	time.sleep(5)

for i in range(1,33):
	querystring = {"league": "78", "season":"2020", 'page' : i}
	response = requests.get(url, headers=headers, params=querystring)
	content = response.json()
	result.append(content)
	print(f"Getting Bundesliga data from page {i}")
	time.sleep(5)

for i in range(1,45):
	querystring = {"league": "135", "season":"2020", 'page' : i}
	response = requests.get(url, headers=headers, params=querystring)
	content = response.json()
	result.append(content)
	print(f"Getting Serie A data from page {i}")
	time.sleep(5)

for i in range(1,38):
	querystring = {"league": "140", "season":"2020", 'page' : i}
	response = requests.get(url, headers=headers, params=querystring)
	content = response.json()
	result.append(content)
	print(f"Getting La Liga data from page {i}")
	time.sleep(5)

len(result)

result[0]

result[0]['response'][0]['statistics'][0]

players = []

for elem in result:
  for player in elem['response']:
    players.append({
      'Name': player['player']['name'],
      'Age': player['player']['age'],
      'Height': player['player']['height'],
      'Weight': player['player']['weight']})

records = []

for elem in result:
  for piece in elem['response']:
    for stat in piece['statistics']:
        records.append({
              'Position': stat['games']['position'],
              'Apps': stat['games']['appearences'],
              'Total minutes': stat['games']['minutes'],
              'Scored goals': stat['goals']['total'],
              'Assists': stat['goals']['assists'],
              'Total shots': stat['shots']['total'],
              'Shots on goal': stat['shots']['on'],
              'Duels total': stat['duels']['total'],
              'Duels won': stat['duels']['won'],
              'Dribble attempts': stat['dribbles']['attempts'],
              'Dribbles succ.': stat['dribbles']['success'],
              'Total duels': stat['duels']['total'],
              'Duels won': stat['duels']['won'],
              'Total passes': stat['passes']['total'],
              'Key passes': stat['passes']['key'],
              'Tackles': stat['tackles']['total'],
              'Blocks': stat['tackles']['blocks'],
              'Interceptions': stat['tackles']['interceptions'],
              'Total saves': stat['goals']['saves'],
              'Goals conceded': stat['goals']['conceded'],
              'Fouls drawn': stat['fouls']['drawn'],
              'Fouls committed': stat['fouls']['committed'],
              'Yellow cards': stat['cards']['yellow'],
              'Red cards for 2nd yellow': stat['cards']['yellowred'],
              'Straight red cards': stat['cards']['red'],
              'Penalties won': stat['penalty']['won'],
              'Penalties scored': stat['penalty']['scored'],
              'Penalties missed': stat['penalty']['missed'],
              'Penalties committed': stat['penalty']['commited'],
              'Penalties saved': stat['penalty']['saved']
        })

players_df = pd.DataFrame(players)
records_df = pd.DataFrame(records)

df = pd.concat([players_df, records_df], axis=1, join='inner')

df

df.to_csv('Top5leagues.csv', index=False)